/* Generated by firmware/generate_pins.py from docs/PINOUT.md; do not edit. */
#pragma once
#include "sdkconfig.h"

#define J1_PIN_3V3 1
#define J1_PIN_GND 2
#define J1_PIN_MOSI 3
#define J1_PIN_MISO 4
#define J1_PIN_SCLK 5
#define J1_PIN_SEL 6
#define J1_PIN_IRQ 7
#define J1_PIN_RESET 8
#define J1_PIN_SLP_TR 9
#define PIN_MOSI CONFIG_AT86RF233_PIN_MOSI
#define PIN_MISO CONFIG_AT86RF233_PIN_MISO
#define PIN_SCLK CONFIG_AT86RF233_PIN_SCLK
#define PIN_SEL CONFIG_AT86RF233_PIN_SEL
#define PIN_IRQ CONFIG_AT86RF233_PIN_IRQ
#define PIN_RESET CONFIG_AT86RF233_PIN_RESET
#define PIN_SLP_TR CONFIG_AT86RF233_PIN_SLP_TR
