#!/usr/bin/env python3
"""Generate main/pins.h from the J1 rows in docs/PINOUT.md."""
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parents[1]
source = root / "docs/PINOUT.md"
output = Path(__file__).parent / "main/pins.h"
rows = [(int(pin), net) for pin, net in re.findall(r"^\| J1 \| (\d+) \| ([A-Z0-9_]+) \|$", source.read_text(), re.M)]
expected = [(1, "3V3"), (2, "GND"), (3, "MOSI"), (4, "MISO"), (5, "SCLK"), (6, "SEL"), (7, "IRQ"), (8, "RESET"), (9, "SLP_TR")]
if rows != expected:
    raise SystemExit(f"unexpected J1 pinout: {rows}")
lines = [
    "/* Generated by firmware/generate_pins.py from docs/PINOUT.md; do not edit. */",
    "#pragma once",
    "#include \"sdkconfig.h\"",
    "",
]
for pin, net in rows:
    lines.append(f"#define J1_PIN_{net} {pin}")
for _, net in rows[2:]:
    lines.append(f"#define PIN_{net} CONFIG_AT86RF233_PIN_{net}")
text = "\n".join(lines) + "\n"
if "--check" in sys.argv:
    if not output.exists() or output.read_text() != text:
        raise SystemExit("firmware/main/pins.h is stale; run firmware/generate_pins.py")
else:
    output.write_text(text)
